name: Unit Tests

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: sudo cmake build-unix
    - name: Run Make
      run: cd build-unix; sudo make
  tests:
    steps:
      - name: Run Tests
        run: cd build-unix/test; ./tests -s
  
    