name: Unit Tests

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Run Make
      run: cmake --build ${{github.workspace}}/build
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: cd ${{github.workspace}}/build/test; ./tests -s
  
    